module Raft

using Random

include("Types.jl")
include("Messages.jl")
include("Transitions.jl")
include("Invariants.jl")
include("Client.jl")

export NodeID,
    Term,
    LogIndex,
    Role,
    Follower,
    Candidate,
    Leader,
    TimerKind,
    ElectionTimer,
    HeartbeatTimer,
    RaftConfig,
    quorum_size,
    RequestID,
    Command,
    PutCommand,
    DeleteCommand,
    GetCommand,
    NoOpCommand,
    CommandResult,
    LogEntry,
    DurableState,
    DurableSnapshot,
    AppendProbe,
    AppliedRecord,
    VolatileState,
    RaftNode,
    last_log_index,
    last_log_term,
    peer_ids,
    RaftMessage,
    RequestVoteRequest,
    RequestVoteResponse,
    AppendEntriesRequest,
    AppendEntriesResponse,
    ClientRequest,
    ClientStatus,
    ClientCommitted,
    ClientNotLeader,
    ClientResponse,
    NodeInput,
    TimerInput,
    MessageInput,
    ClientInput,
    CrashInput,
    RecoverInput,
    RaftEffect,
    SendMessage,
    ResetTimer,
    CancelTimer,
    PersistState,
    ReplyClient,
    initialize!,
    handle!,
    InvariantViolation,
    InvariantAudit,
    InvariantReport,
    check_invariants!,
    assert_invariants!,
    AuditedCluster,
    transition!,
    HistoryOperation,
    ClientHistory,
    record_invocation!,
    record_completion!,
    is_linearizable,
    deterministic_workload

end
